matches: matches
home_team: match_localteam_name
away_team: match_visitorteam_name
match_home_team_score: match_localteam_score
match_away_team_score: match_visitorteam_score
ht_score: match_ht_score
ft_score: match_ft_score
match_time: match_time
match_status: match_status
events: match_events
type: event_type
time: event_minute
team: event_team
player: event_player
event_result: event_result
error: ERROR
server: ServerName
first_half: first_half
second_half: second_half
FIRST_HALF: first_half
SECOND_HALF: second_half
HOME_TEAM: localteam
AWAY_TEAM: visitorteam
GOAL: goal
YELLOWCARD: yellowcard
REDCARD: redcard
NO_EFFECT_ON_SCORE: ""
NO_ERROR: OK
NO_MATCH_TODAY: no matches found today
FOOTBALL_API_MOCK: Football-API-Mock
HALF_TIME: HT
FULL_TIME: FT
MATCH_FINISHED: ""
SCORE_NOT_REACHED: ""
